### ISSUE TITLE
Unsupported type: 0xA0

### ISSUE THREAD

**Issue by uthaman** [tuliomagalhaes/Ethernetip4j#2]
Hi,
When trying to a I/O Message type, getting the below exception

se.opendataexchange.ethernetip4j.exceptions.InvalidTypeException: Unsupported type: 0xA0
    at se.opendataexchange.ethernetip4j.EthernetIpDataTypeValidator.getValues(EthernetIpDataTypeValidator.java:125)
    at se.opendataexchange.ethernetip4j.segments.CipMessageRouterResponse.getValue(CipMessageRouterResponse.java:53)
    at se.opendataexchange.ethernetip4j.segments.CipMultipleMessageRouterResponse.getValue(CipMultipleMessageRouterResponse.java:48)
    at se.opendataexchange.ethernetip4j.segments.CipPacketResponse.getValue(CipPacketResponse.java:163)
    at se.opendataexchange.ethernetip4j.services.UnconnectedMessageManagerResponse.getValue(UnconnectedMessageManagerResponse.java:59)
    at se.opendataexchange.ethernetip4j.clx.SimpleLogixCommunicator.read(SimpleLogixCommunicator.java:77)
    at se.opendataexchange.ethernetip4j.test.TestClass.main(TestClass.java:33)

**Comment by tuliomagalhaes** [comment]
Hello, I'm not the creator of the lib. But I think your PLC is not
compatible.

2016-06-22 10:36 GMT-03:00 Uthaman notifications@github.com:

**Comment by uthaman** [comment]
Hi, The PLC I'm using is  Allen Bradley 1768-ENBT/A. This error is happening only for the tag type I/O Message, is there any other way to read and write on String types?

**Comment by tuliomagalhaes** [comment]
Hmm... maybe the protocol changed.

2016-06-22 10:59 GMT-03:00 Uthaman notifications@github.com:
